### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by LoneDev6**

### CODE REVIEW

**Comment by MelonCode** [comment]
Hey, why do we need task speed, if we already have an update speed which?

**Comment by LoneDev6** [comment]
If anyone wants to reduce the speed more

**Comment by MelonCode** [comment]
@LoneDev6 So, just reduce update speed :D

**Comment by LoneDev6** [comment]
You can delete this from the update then, thanks

**Comment by MelonCode** [comment]
Thanks for contribution and for readme page :)
I'll add you to contributors on spigot page

**Comment by LoneDev6** [comment]
No problem ;) Performance now is good, i see 0% usage on timings instead of 300+%.
Problem was that plugin was loading chunk when spawning particles.

**Comment by MelonCode** [comment]
Yeah, I saw it.
Strange that nobody was complaining about it for years :D
I think it's because cost of keeping chunks loaded is really higher in modern versions

**Comment by LoneDev6** [comment]
Probably something changed in Minecraft 1.13+ and now chunk loading is more resource intensive or something like that

**Comment by MelonCode** [comment]
@LoneDev6 How can I contact you aside from spigot forum and here? 
Like discord, telegram, steam, etc?

**Comment by LoneDev6** [comment]
Discord LoneDev#7444

**Pull request merged**
